development:
  adapter: postgresql
  database: foodlog
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: foodlog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: foodlog_production
  pool: 5
  timeout: 5000
